### ISSUE TITLE
Open Images Download: 'mv argument list too long'

### ISSUE THREAD

**Issue by michalsr** [allenai/grit_official#1]
If you get the error 'mv argument list too long' on [https://github.com/allenai/grit_official/blob/main/download/images.py#L69](https://github.com/allenai/grit_official/blob/main/download/images.py#L69) then you might have to use shutil or similar package to complete

**Comment by RyanMarten** [comment]
Addressed in [1956be4](https://github.com/allenai/grit_official/commit/1956be4a92aedd2e89b301d2392a661b87563de6)
